name: luyando
description: Luyando AI Assistant
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.2.0
  shared_preferences: ^2.2.2
  speech_to_text: ^6.6.0
  flutter_tts: ^3.8.3
  file_picker: ^5.5.0

flutter:
  uses-material-design: true
